### ISSUE TITLE
Integrate with AWS-SSO for authentication

### ISSUE THREAD

**Issue by statik** [kindlyops/murderhornet#1]
In order to drive cloudformation stacks, the app needs AWS credentials. Don't ask users to manage credentials manually.

AWS-SSO implements OIDC:
* https://docs.aws.amazon.com/cli/latest/reference/sso-oidc/
* Walkthrough of process: https://github.com/99designs/aws-vault/issues/449#issue-520446124

Promising library for OIDC in electron: https://github.com/openid/AppAuth-JS

As a workaround before this is implemented, use `aws-vault` to get credentials and then run murderhornet from there.

**Comment by urz9999** [comment]
Maybe you can also give a try to our open-source project: [https://github.com/Noovolari/leapp](https://github.com/Noovolari/leapp). It deals with AWS SSO authentication and accounts/roles retrieval then it creates short-lived temporary credentials in .aws/credentials to maximize compatibility with third party tools / sdks.

**Comment by crashGoBoom** [comment]
Initial implementation of AWS SSO is in place.
